// <auto-generated />
using Fitotron5000.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Fitotron5000.Migrations
{
    [DbContext(typeof(fitotron_devContext))]
    [Migration("20180314053958_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fitotron5000.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("CurrentWeight")
                        .HasColumnName("currentWeight")
                        .HasColumnType("float");

                    b.Property<long>("DiscordId")
                        .HasColumnName("_discordID");

                    b.Property<double?>("Goal")
                        .HasColumnName("goal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fitotron5000.Models.Weights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnName("timeStamp")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnName("userId");

                    b.Property<double?>("UserWeight")
                        .HasColumnName("userWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("Fitotron5000.Models.Weights", b =>
                {
                    b.HasOne("Fitotron5000.Models.Users", "User")
                        .WithMany("Weights")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_weights_users")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
